version: '3.8'

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-01-25T19-56-04Z
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  mongodb:
    image : mongo:5.0.0-rc2-focal
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass        
    volumes:
      - ./conf/db01/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/db01:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  redis:
    image: 'redis:6'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./conf/redis01:/opt/redis-conf
      - ./conf/redis01/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis01:/data
    ports:
      - '6379:6379'

  apps:
    image: nginx:stable
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
  
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio:
    image: nginx:1.19.2-alpine
    hostname: minio
    volumes:
      - ./minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/img-logo;
      /usr/bin/mc mb myminio/company-docs;
      /usr/bin/mc mb myminio/claims-docs;
      exit 0
      "

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:

networks:
  default:
    name: app0-network
