"""
mail module
"""
# platform mails
MAIL_WELCOME = 'welcome'
MAIL_EMAIL_CONFIRMATION = 'email_confirmation'
MAIL_PASSWORD_RESET = 'password_reset'
MAIL_PASSWORD_RESET_OK = 'password_reset_ok'

# replacements keys
VAR_CONTENT = 'VAR_CONTENT'
VAR_USER_NAME = 'VAR_USER_NAME'
VAR_ADMIN_APP_URL = 'VAR_ADMIN_APP_URL'
VAR_PASSWORD_RESET_URL = 'VAR_PASSWORD_RESET_URL'
VAR_EMAIL_CONFIRM_URL = 'VAR_EMAIL_CONFIRM_URL'
