"""
mail module
"""
from app0.admin.services import IDX_BASE_MAIL, IDX_COMPANY_MAIL

MAIL_COLLECTION_BASE = IDX_BASE_MAIL
MAIL_COLLECTION_ATTENDANT = IDX_COMPANY_MAIL

# platform mails
MAIL_WELCOME = 'welcome'
MAIL_EMAIL_CONFIRMATION = 'email_confirmation'
MAIL_PASSWORD_RESET = 'password_reset'
MAIL_PASSWORD_RESET_OK = 'password_reset_ok'

# attendant mails
MAIL_CLAIM_OPEN = 'claim_open'
MAIL_CLAIM_OPEN_ESTIMATOR = 'claim_open_estimator'
MAIL_CLAIM_INSPECTION = 'claim_inspection'
MAIL_CLAIM_MITIGATION = 'claim_mitigation'
MAIL_CLAIM_RECEIPTS = 'claim_receipts'
MAIL_CLAIM_ESTIMATION = 'claim_estimation'
MAIL_CLAIM_SPOL_CLIENT = 'claim_spol_client'
MAIL_CLAIM_SPOL_IC = 'claim_spol_ic'
MAIL_RESOLUTION_RELEASE_CLIENT = 'resolution_release_client'
MAIL_RESOLUTION_RELEASE_IC = 'resolution_release_ic'
MAIL_RESOLUTION_APPRAISAL = 'resolution_appraisal'
MAIL_RESOLUTION_UMPIRE_ACK_CLIENT = 'resolution_umpire_ack_client'
MAIL_RESOLUTION_UMPIRE_ESX_REQUIRE = 'resolution_umpire_esx_require'
MAIL_RESOLUTION_UMPIRE_ESX_UMPIRE = 'resolution_umpire_esx_umpire'
MAIL_RESOLUTION_ATTORNEY_RETAINER_CLIENT = 'resolution_attorney_retainer_client'
MAIL_RESOLUTION_ATTORNEY_RETAINER = 'resolution_attorney_retainer'

# replacements keys
VAR_CONTENT = 'VAR_CONTENT'
VAR_USER_NAME = 'VAR_USER_NAME'
VAR_CLAIMS_APP_URL = 'VAR_CLAIMS_APP_URL'
VAR_PASSWORD_RESET_URL = 'VAR_PASSWORD_RESET_URL'
VAR_EMAIL_CONFIRM_URL = 'VAR_EMAIL_CONFIRM_URL'

# replacements attendant keys
VAR_COMPANY_ADDRESS = 'VAR_COMPANY_ADDRESS'
VAR_COMPANY_PHONE = 'VAR_COMPANY_PHONE'
VAR_COMPANY_LOGO_URL = 'VAR_COMPANY_LOGO_URL'
VAR_COMPANY_NAME = 'VAR_COMPANY_NAME'
VAR_CLAIM_NUMBER = 'VAR_CLAIM_NUMBER'
VAR_CLAIM_FILE_NUMBER = 'VAR_CLAIM_FILE_NUMBER'
VAR_CLAIM_VIEW_URL = 'VAR_CLAIM_VIEW_URL'
VAR_INSPECTION_TYPE = 'VAR_INSPECTION_TYPE'
VAR_INSPECTION_ADDRESS = 'VAR_INSPECTION_ADDRESS'
VAR_INSPECTION_DATE = 'VAR_INSPECTION_DATE'
VAR_CLIENT_NAME = 'VAR_CLIENT_NAME'
VAR_SPOL_CLIENT_UPLOAD_URL = 'VAR_SPOL_CLIENT_UPLOAD_URL'
VAR_RELEASE_CLIENT_UPLOAD_URL = 'VAR_RELEASE_CLIENT_UPLOAD_URL'
VAR_UMPIRE_ACK_CLIENT_UPLOAD_URL = 'VAR_UMPIRE_ACK_CLIENT_UPLOAD_URL'
VAR_RETAINER_CLIENT_UPLOAD_URL = 'VAR_RETAINER_CLIENT_UPLOAD_URL'
